stages:
  - build
  - test

build-job:
  stage: build
  image: python-3.10
  script:
    - echo "Creating virtual environment for the project..."
    - virtualenv $(pwd)/venv
    - source $(pwd)/venv/Scripts/activate
    - echo "Installing requirements..."
    - pip install --no-cache-dir -r requirements.txt
    - deactivate

  artifacts:
    paths:
      - $(pwd)/venv
  tags:
    - nouvelles

test-job:
  stage: test
  script:
    - echo "Activating virtual environment..."
    - source $(pwd)/venv/Scripts/activate
    - echo "Running unit tests"
    - python manage.py test
    - deactivate
    - echo "All tests successfully passed."